### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by andrewshadura** [pwithnall/dbus-deviation#17]
```
======================================================================
ERROR: test_duplicate (dbusapi.tests.test_ast.TestAstLogging)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/dbus-deviation/dbusapi/tests/test_ast.py", line 248, in test_duplicate
    'AMethod': method,
  File "/tmp/dbus-deviation/dbusapi/ast.py", line 318, in __init__
    for child in (methods or {}).values() + (signals or {}).values() + \
TypeError: unsupported operand type(s) for +: 'dict_values' and 'dict_values'

======================================================================
ERROR: test_annotation_argument (dbusapi.tests.test_ast.TestAstNames)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/dbus-deviation/dbusapi/tests/test_ast.py", line 148, in test_annotation_argument
    'AMethod': method,
  File "/tmp/dbus-deviation/dbusapi/ast.py", line 318, in __init__
    for child in (methods or {}).values() + (signals or {}).values() + \
TypeError: unsupported operand type(s) for +: 'dict_values' and 'dict_values'
…
```

**Comment by andrewshadura** [comment]
Sorry for the noise, I was running an outdated version.
